#if defined(ING)

#define		MSG1	"Couldn`t open map file"
#define		MSG2	"File doesn´t seems to be correct"
#define		MSG3	"Couldn´t access device :\n\n"
#define		MSG4	"Joystick ready, press LAUNCH to activate it"
#define		MSG5	"There was an error sending data to driver"
#define		MSG6	"New mouse configuration sended to driver"
#define		MSG7	"There was an error reading command file"
#define		MSG8	"There was an error creating file"
#define		MSG9	"Couldn´t open command file for write"
#define		MSG10	"File saved"
#define		MSG11	"Maximum 10 position"
#define		MSG12	"Warning"
#define		MSG13	"Name is empty"
#define		MSG14	"The name is repeated"
#define		MSG15	"Maximum 8 key pulsations"
#define		MSG16	"The file already exists"
#define		MSG17	"Couldn´t open .X36 file"
#define		MSG18	"Couldn´t open .CMM file\n\n.CMM and .X36 files must be in\nthe same directory to import them."
#define		MSG19	"There was an error translating .X36 file"
#define		MSG20	"Maximum 6 positions"
#define		MSG21	"Couldn´t run raton.exe"
#define		MSG22	"Save data before exit?"
#define		MSG23	"There was an error saving data to registry"
#define		MSG24	"No joystick has been detected"
#define		MSG25	"Failed to save data ( x axis )"
#define		MSG26	"Failed to save data ( y axis )"
#define		MSG27	"Failed to save data ( z axis )"
#define		MSG28	"Failed to save data ( r axis )"
#define		MSG29	"There was an error translating .xmp file"

#define		TIP0	"Report / Print"
#define		TIP1	"Save data"
#define		TIP2	"Command editor"
#define		TIP3	"<None>"
#define		TIP4	"Button"
#define		TIP5	"X axis"
#define		TIP6	"Y axis"
#define		TIP12	"Name"
#define		TIP13	"Keys"
#define		TIP14	"<Pinkie mode On>"
#define		TIP15	"<Pinkie mode Off>"
#define		TIP16	"<Mode 1>"
#define		TIP17	"<Mode 2>"
#define		TIP18	"<Mode 3>"
#define		TIP19	"Button"
#define		TIP20	"Port"
#define		TIP21	"Press"
#define		TIP22	"Release"
#define		TIP23	"Press (Pinkie)"
#define		TIP24	"Release (Pinkie)"
#define		TIP25	"Yes"
#define		TIP26	"<Increment>"
#define		TIP27	"<Positions>"
#define		TIP28	"<Mouse Up>"
#define		TIP29	"<Mouse Down>"
#define		TIP30	"<Mouse Left>"
#define		TIP31	"<Mouse Right>"
#define		TIP32	"<Mouse Left Button>"
#define		TIP33	"<Mouse Right Button>"

#define		BTN1	"Throttle (X35)"
#define		BTN2	"Mode 1"
#define		BTN3	"Mode 2"
#define		BTN4	"Mode 3"
#define		BTN5	"No Modes"
#define		BTN6	"Trigger"
#define		BTN7	"Launch"
#define		BTN8	"Button A"
#define		BTN9	"Button B"
#define		BTN10	"Button C"
//#define		BTN11	"Pinkie"
#define		BTN12	"Hat 1 Up"
#define		BTN13	"Hat 1 Down"
#define		BTN14	"Hat 1 Left"
#define		BTN15	"Hat 1 Right"
#define		BTN16	"Hat 2 Up"
#define		BTN17	"Hat 2 Down"
#define		BTN18	"Hat 2 Left"
#define		BTN19	"Hat 2 Right"
#define		BTN20	"Button D"
#define		BTN21	"Mouse button"
#define		BTN22	"Mode Left"
#define		BTN23	"Mode Right"
#define		BTN24	"Aux Left"
#define		BTN25	"Aux Right"
#define		BTN26	"Mouse hat Up"
#define		BTN27	"Mouse hat Down"
#define		BTN28	"Mouse hat Left"
#define		BTN29	"Mouse hat Right"
#define		BTN30	"Hat 3 Up"
#define		BTN31	"Hat 3 Down"
#define		BTN32	"Hat 3 Left"
#define		BTN33	"Hat 3 Right"
#define		BTN34	"Rotary 1"
#define		BTN35	"Rotary 2"
#define		BTN36	"Throttle"
#define		BTN37	"Rudder"
#define		BTN38	"Hat 1 Up-Left"
#define		BTN39	"Hat 1 Up-Right"
#define		BTN40	"Hat 1 Down-Left"
#define		BTN41	"Hat 1 Down-Right"
#define		BTN42	"Hat 2 Up-Left"
#define		BTN43	"Hat 2 Up-Right"
#define		BTN44	"Hat 2 Down-Left"
#define		BTN45	"Hat 2 Down-Right"
#endif


#if defined(ESP)

#define		MSG1	"No se pudo abrir el archivo de mapa"
#define		MSG2	"No parece que el archivo sea correcto"
#define		MSG3	"No se pudo acceder al dispositivo :\n\n"
#define		MSG4	"Joystick listo, pulsa LANZAR para activarlo"
#define		MSG5	"Hubo un error al enviar los datos al driver"
#define		MSG6	"Nueva configuración enviada al controlador"
#define		MSG7	"Hubo un error al leer el archivo de comandos"
#define		MSG8	"Hubo un error al crear archivo"
#define		MSG9	"No se pudo abrir el archivo de comandos para guardar"
#define		MSG10	"Archivo guardado correctamente"
#define		MSG11	"Máximo 10 posiciones"
#define		MSG12	"Advertencia"
#define		MSG13	"Campo nombre vacío"
#define		MSG14	"El nombre está repetido"
#define		MSG15	"Máximo 8 pulsaciones"
#define		MSG16	"El archivo ya existe"
#define		MSG17	"No se pudo abrir el archivo .X36"
#define		MSG18	"No se pudo abrir el archivo .CMM\n\nLos archivos .CMM y .X36 deben estar en\nel mismo directorio para importarlos."
#define		MSG19	"Hubo un error grave traduciendo el archivo .X36"
#define		MSG20	"Máximo 6 posiciones"
#define		MSG21	"No se pudo ejecutar raton.exe"
#define		MSG22	"¿Guardar datos antes de salir?"
#define		MSG23	"Hubo un error al guardar los datos en el registro"
#define		MSG24	"No se detectó ningún joystick"
#define		MSG25	"Error al guardas datos ( eje x )"
#define		MSG26	"Error al guardas datos ( eje y )"
#define		MSG27	"Error al guardas datos ( eje z )"
#define		MSG28	"Error al guardas datos ( eje r )"
#define		MSG29	"Hubo un error grave traduciendo el archivo .xmp"

#define		TIP0	"Resumen / Imprimir"
#define		TIP1	"Guardar datos"
#define		TIP2	"Editor de comandos"
#define		TIP3	"<Ninguno>"
#define		TIP4	"Botón"
#define		TIP5	"Eje X"
#define		TIP6	"Eje Y"
#define		TIP12	"Nombre"
#define		TIP13	"Teclas"
#define		TIP14	"<Modo Pinkie Encendido>"
#define		TIP15	"<Modo Pinkie Apagado>"
#define		TIP16	"<Modo 1>"
#define		TIP17	"<Modo 2>"
#define		TIP18	"<Modo 3>"
#define		TIP19	"Botón"
#define		TIP20	"Puerto"
#define		TIP21	"Apretar"
#define		TIP22	"Soltar"
#define		TIP23	"Apretar (Pinkie)"
#define		TIP24	"Soltar (Pinkie)"
#define		TIP25	"Sí"
#define		TIP26	"<Incremental>"
#define		TIP27	"<Posiciones>"
#define		TIP28	"<Ratón Arriba>"
#define		TIP29	"<Ratón Abajo>"
#define		TIP30	"<Ratón Izquierda>"
#define		TIP31	"<Ratón Derecha>"
#define		TIP32	"<Ratón, Botón Izquierdo>"
#define		TIP33	"<Ratón, Botón Derecho>"

#define		BTN1	"Acelerador (X35)"
#define		BTN2	"Modo 1"
#define		BTN3	"Modo 2"
#define		BTN4	"Modo 3"
#define		BTN5	"Sin Modos"
#define		BTN6	"Gatillo"
#define		BTN7	"Lanzar"
#define		BTN8	"Botón A"
#define		BTN9	"Botón B"
#define		BTN10	"Botón C"
//#define		BTN11	"Pinkie"
#define		BTN12	"Seta 1 Arriba"
#define		BTN13	"Seta 1 Abajo"
#define		BTN14	"Seta 1 Izquierda"
#define		BTN15	"Seta 1 Derecha"
#define		BTN16	"Seta 2 Arriba"
#define		BTN17	"Seta 2 Abajo"
#define		BTN18	"Seta 2 Izquierda"
#define		BTN19	"Seta 2 Derecha"
#define		BTN20	"Botón D"
#define		BTN21	"Botón Ratón"
#define		BTN22	"Modo Izquierda"
#define		BTN23	"Modo Derecha"
#define		BTN24	"Auxiliar Izquierda"
#define		BTN25	"Auxiliar Derecha"
#define		BTN26	"Seta ratón Arriba"
#define		BTN27	"Seta ratón Abajo"
#define		BTN28	"Seta ratón Izquierda"
#define		BTN29	"Seta ratón Derecha"
#define		BTN30	"Seta 3 Arriba"
#define		BTN31	"Seta 3 Abajo"
#define		BTN32	"Seta 3 Izquierda"
#define		BTN33	"Seta 3 Derecha"
#define		BTN34	"Giratorio 1"
#define		BTN35	"Giratorio 2"
#define		BTN36	"Acelerador"
#define		BTN37	"Pedales"
#define		BTN38	"Seta 1 Arriba-Izquierda"
#define		BTN39	"Seta 1 Arriba-Derecha"
#define		BTN40	"Seta 1 Abajo-Izquierda"
#define		BTN41	"Seta 1 Abajo-Derecha"
#define		BTN42	"Seta 2 Arriba-Izquierda"
#define		BTN43	"Seta 2 Arriba-Derecha"
#define		BTN44	"Seta 2 Abajo-Izquierda"
#define		BTN45	"Seta 2 Abajo-Derecha"

#endif