//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by X36Map.rc
//
#define IDR_MANIFEST                    1
#define IDD_X36MAP_DIALOG               102
#define IDD_X36MAP_EDITOR               103
#define IDD_X36MAP_EDITOR_BOTONES       104
#define IDD_X36MAP_EDITOR_EJES          105
#define IDD_X36MAP_NUEVO                106
#define IDD_X36MAP_COMANDOS             107
#define IDD_X36MAP_CMD_EDITAR           108
#define IDD_X36MAP_RESUMEN              109
#define IDD_X36MAP_ACERCADE             110
#define IDD_X36MAP_CALIBRAR             111
#define IDI_Principal                   120
#define IDB_TOOLBAR                     121
#define IDI_ICON3                       122
#define IDR_MENU_ESP                    123
#define IDR_MENU_ING                    124
#define ID_ARCHIVO_GUARDAR              130
#define ID_ARCHIVO_GUARDARCOMO          131
#define ID_ARCHIVO_SALIR                132
#define ID_VER_COMANDOS                 133
#define ID_VER_RESUMEN                  134
#define ID_SOBRE_SOBREELX36MAP          135
#define IDD_ACERCADE                    136
#define IDR_VERSION2                    137
#define ID0Cargar                       1000
#define ID0Editar                       1001
#define ID0ListaMapas                   1002
#define ID0Salir                        1003
#define ID0Nuevo                        1004
#define ID0Actualizar                   1005
#define ID1Nombre                       1006
#define IDTab1                          1007
#define IDTab2                          1008
#define IDTab3                          1009
#define IDbEditorComandos               1010
#define IDbGuardar                      1011
#define IDModos                         1012
#define IDPinkie                        1013
#define IDIncremental                   1014
#define IDPosiciones                    1015
#define IDIncrementalPk                 1016
#define IDPosicionesPk                  1017
#define IDLabelConPinkieG               1018
#define IDLabelIncrementar              1023
#define IDLabelDecrementar              1024
#define IDLabelIncrementarPk            1025
#define IDLabelDecrementarPk            1026
#define IDComboApr                      1027
#define IDComboAprPk                    1028
#define IDComboSol                      1029
#define IDComboSolPk                    1030
#define IDComboPuerto                   1031
#define IDLabelConPinkie                1032
#define IDAsigPuertoBt                  1034
#define IDLabelApretar                  1035
#define IDLabelSoltar                   1036
#define IDLabelApretarPk                1037
#define IDLabelSoltarPk                 1038
#define IDListaCmds                     1039
#define IDListaCmdsPk                   1040
#define IDListaCmdsP                    1040
#define IDListaPos                      1041
#define IDListaPosPk                    1042
#define IDLabelPos                      1043
#define IDLabelPosPk                    1044
#define IDLabelComandos                 1045
#define IDLabelComandosPk               1046
#define IDbBorrarPk                     1047
#define IDbInsertar                     1048
#define IDbBorrar                       1049
#define IDbInsertarPk                   1050
#define ID2Nuevo                        1051
#define ID2Editar                       1052
#define ID2Borrar                       1053
#define ID2ListaComandos                1054
#define ID3Nombre                       1055
#define ID3InsTecla                     1056
#define ID3BoTecla                      1057
#define ID3Pulsaciones                  1058
#define ID3ListaTeclas                  1059
#define ID3Guardar                      1060
#define IDAutoRepeat                    1061
#define IDAutoRepeatPk                  1062
#define IDComboPOV                      1065
#define IDAsigPuertoPOV                 1067
#define IDbResumen                      1068
#define ID4Lista1                       1069
#define ID4Lista2                       1070
#define ID4Lista3                       1071
#define ID4Imprimir                     1072
#define ID4Tab                          1073
#define ID2Raton                        1074
#define ID0Importar                     1075
#define IDComboInc                      1076
#define IDComboIncPk                    1077
#define IDComboDec                      1078
#define IDComboDecPk                    1079
#define IDAsigPuertoEj                  1080
#define ID0SensiDes                     1085
#define ID0PreciDes                     1086
#define ID0SensiEd                      1087
#define ID0PreciEd                      1088
#define ID0Cambiar                      1089
#define IDSensibilidad                  1090
#define IDSensibilidadPk                1091
#define IDLabelSensibilidad             1092
#define IDLabelSensibilidadPk           1093
#define IDLabelMax                      1094
#define IDLabelMin                      1095
#define IDLabelMaxPk                    1096
#define IDLabelMinPk                    1097
#define IDC_HOTKEY1                     1098
#define ID0Calibrar                     1099
#define ID6Escalax1                     1100
#define ID6Escalax2                     1101
#define ID6ZNulax0                      1102
#define ID6ZNulax1                      1103
#define ID6ZNulax2                      1104
#define ID6Reglaxr                      1105
#define ID6Reglaxv                      1106
#define ID6Botonx                       1107
#define ID6xrmin                        1108
#define ID6xrval                        1109
#define ID6xrmax                        1110
#define ID6xvmin                        1111
#define ID6xvval                        1112
#define ID6xvmax                        1113
#define ID6Escalay1                     1114
#define ID6Escalay2                     1115
#define ID6ZNulay0                      1116
#define ID6ZNulay1                      1117
#define ID6ZNulay2                      1118
#define ID6Reglayr                      1119
#define ID6Reglayv                      1120
#define ID6Botony                       1121
#define ID6yrmin                        1122
#define ID6yrval                        1123
#define ID6yrmax                        1124
#define ID6yvmin                        1125
#define ID6yvval                        1126
#define ID6yvmax                        1127
#define ID6Escalaz1                     1128
#define ID6Escalaz2                     1129
#define ID6ZNulaz0                      1130
#define ID6ZNulaz1                      1131
#define ID6ZNulaz2                      1132
#define ID6Reglazr                      1133
#define ID6Reglazv                      1134
#define ID6Botonz                       1135
#define ID6zrmin                        1136
#define ID6zrval                        1137
#define ID6zrmax                        1138
#define ID6zvmin                        1139
#define ID6zvval                        1140
#define ID6zvmax                        1141
#define ID6Escalar1                     1142
#define ID6Escalar2                     1143
#define ID6ZNular0                      1144
#define ID6ZNular1                      1145
#define ID6ZNular2                      1146
#define ID6Reglarr                      1147
#define ID6Reglarv                      1148
#define ID6Botonr                       1149
#define ID6rrmin                        1150
#define ID6rrval                        1151
#define ID6rrmax                        1152
#define ID6rvmin                        1153
#define ID6rvval                        1154
#define ID6rvmax                        1155
#define ID6Coger                        1156
#define ID6Borrar                       1157
#define ID6Centrox                      1158
#define ID6Centroy                      1159
#define ID6Centroz                      1160
#define ID6Centror                      1161
#define ID0Seleccionar                  1162
#define ID0Activada                     1163
#define ID0LabelMapa                    1165
#define IDEjeX                          1166
#define IDEjeY                          1167
#define IDEjeZ                          1168
#define IDEjeR                          1169
#define IDC_COMBO1                      1170

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1171
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
